---
# Development environment override
services:
    php:
        ports:
            - "8023:80"
        build:
            context: .
            target: frankenphp_dev
        volumes:
            - ./:/app
            - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
            - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
            # If you develop on Mac or Windows you can remove the vendor/ directory
            #  from the bind-mount for better performance by enabling the next line:
            #- /app/vendor
        environment:
            FRANKENPHP_WORKER_CONFIG: watch
            MERCURE_EXTRA_DIRECTIVES: demo
            # See https://xdebug.org/docs/all_settings#mode
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
            APP_ENV: "${APP_ENV:-dev}"
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway
        tty: true
        depends_on:
            database:
                condition: service_healthy

    database:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shoptet_api_bridge
            MYSQL_USER: vojta
            MYSQL_PASSWORD: root
        ports:
            - "3099:3306"
        volumes:
            - database_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 30s
    adminer:
        image: adminer:latest
        ports:
            - "8080:8080"
        environment:
            ADMINER_DEFAULT_SERVER: database
        depends_on:
            - database

volumes:
    database_data:

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
